# Generated by Django 5.2.2 on 2025-06-09 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renamed_filename', models.CharField(max_length=255)),
                ('page_count', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('file_path', models.FileField(upload_to='processed/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='order.printorder')),
            ],
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
